- name: install and run nginx
  hosts: web
  become: yes
  tasks: 
  -name: installing nginx
   ansible.builtin.dnf:
     name: nginx
     state: latest
  -name: start nginx
   ansible.builtin.servive:
     name: nginx
     state: started
     enable: yes

