- name: variables
  hosts: localhost
  vars:
    course: "terraform"
    trainer: "Siva"
    duration: "120days"
  tasks: 
   - name: "print information"
     ansible.builtin.debug:
      msg: "Hi I am learning {{course}} from trainer {{trainer}} and duration is {{duration}}."